---
addons:
  apt:
    sources:
      - ppa:ubuntu-sdk-team/ppa
    packages:
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5webkit5-dev
      - libsqlite3-dev
      - qt5-default
      - qttools5-dev-tools

script:
  - make test
  - find ./build/test/bin -type f -print0 | xargs -n 1 -0
