---
language: cpp

matrix:
 include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=56
  - os: osx
    compiler: clang
    env:
     - QT_BASE=56
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=57
  - os: osx
    compiler: clang
    env:
     - QT_BASE=57
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=58
  # - os: osx
  #   compiler: clang
  #   env:
  #    - QT_BASE=58

before_install:
  - if [[ "$QT_BASE" = "55" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
  - if [[ "$QT_BASE" = "56" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - if [[ "$QT_BASE" = "57" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y; fi
  - if [[ "$QT_BASE" = "58" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  - if [ "$QT_BASE" = "55" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq qt55base; source /opt/qt55/bin/qt55-env.sh;
      else
        brew install qt55;
        brew link --force qt55;
      fi
    fi
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
  - if [ "$QT_BASE" = "57" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh;
      else
        brew install qt5;
        brew link --force qt5;
      fi
    fi
  - if [ "$QT_BASE" = "58" ]; then
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq qt58base; source /opt/qt58/bin/qt58-env.sh;
      # else
      #   brew install qt5;
      #   brew link --force qt5;
      fi
    fi

script:
  - make test
  - find ./build/test/bin -type f -print0 | xargs -n 1 -0
